### ISSUE TITLE
Exception: Atom identity function requires startID to be greater than zero

### ISSUE THREAD

**Issue by tinicode** [anskarl/LoMRF#16]
I tried to export the grounding results of an example based on the YAGO dataset. But I received the following exception saying that the startID for Atom identity function is -549940296. Where does this comes from?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/43300855/62574211-3c6fa400-b898-11e9-90e1-a370fa2dbb84.png"> <img width="1280" alt="image" src="https://user-images.githubusercontent.com/43300855/62574194-324da580-b898-11e9-971e-a505f4cc0d95.png"><img width="1276" alt="image" src="https://user-images.githubusercontent.com/43300855/62574161-15b16d80-b898-11e9-8f1e-3c8009f233d9.png">

[example_yago.zip](https://github.com/anskarl/LoMRF/files/3474020/example_yago.zip)

**Comment by anskarl** [comment]
`startID` becomes negative when the domain is too large and in practice the `startID` overflows. Starting from 0 each atom is being assigned into some interval of atom ids. 

For example, assume that we have an atom with 2 arguments `SomeAtom(domain1,domain2)`. The interval will be start from 0 until to the product of domain sizes, i.e. `|domain1| x |domain1|`. Thereafter the next atom will start from the next available id.

At the moment, LoMRF stores atom ids into singed integers and for indexing it only uses the positive integers. 

We should change to `long` numbers (64bit), but until then you may need to give smaller databases in order to have small enough domains.

**Comment by tinicode** [comment]
Ok, thanks a lot @anskarl!
