### ISSUE TITLE
Unexpected inference results

### ISSUE THREAD

**Issue by markos523** [anskarl/LoMRF#22]
Hi everyone, 
I've been experimenting with LoMRF and Alchemy 2 for a couple of days now. Specifically :
1) The following .mln file

flip = {A}
flop = {C}

H(flip)
S(flop)

H(i) v S(o).

when performing inference for the predicates H and S I get the following results.
LoMRF:
H(A) 0.6225
S(C) 0.6228
Alchemy 2:
H(A) 0.660734
S(C) 0.670783

I get similar results by replacing the hard constraint H(i) v S(o). with a heavy weighted formula, i.e. 

flip = {A}
flop = {C}

H(flip)
S(flop)

1000 H(i) v S(o)

In this case the results are 
LoMRF:
H(A) 0.62425
S(C) 0.6232
Alchemy 2:
H(A) 0.671683
S(C) 0.667633

The way I understand these results is the following (please correct me if I am wrong): 
There are essentially 3 combinations of (H(A), S(C)) truth values that make the formula H(i) v S(o) True, that is (True, True),(True,False) and (False, True). These are the most probable values for (H(A), S(C)), therefore, the sampling process produces approximately Pr(H(A)=True) =~ Pr(H(A) = True) =~ 2/3.

2) The .mln file 

flip = {A}
flop = {C}

H(flip)
S(flop)

H(i) => S(o).

when performing inference for the predicates H and S I get the following results.
LoMRF:
H(A) 0.3788
S(C) 0.6263
Alchemy 2:
H(A) 0.331767
S(C) 0.664884

I got similar results from both LoMRF and Alchemy 2, by replacing the hard constraint , 
H(i) => S(o).
with  the heavy weighted formula
1000 H(i) => S(o)

Again, the way I understand these results is the following (please correct me if I am wrong): 
There are essentially 3 combinations of (H(A), S(C)) truth values that make the formula H(i) => S(o) True, that is (True, True),(False,False) and (False, True). These are the most probable values for (H(A), S(C)), therefore, the sampling process produces approximately Pr(H(A)=True) =~ 1/3 and Pr(S(A)=True) =~ 2/3.

3) The unexpected results come from experimenting with the following .mln file:

flip = {A}
flop = {C}

H(flip)
S(flop)

H(i) ^ S(o).

The results I get when inferring H(A) and S(C) are 
LoMRF:
H(A) 0.36755
S(C) 0.38175
Alchemy 2:
H(A) 0.329217
S(C) 0.338016

I can't get my head around these results. Following the previous thoughts, the most probable value for
(H(A), S(C)) is (True, True). The sampling process should produce Pr(H(A)=True) =~ Pr(H(A) = True) =~ 1.

What is even more confusing, is that the .mln file 

flip = {A}
flop = {C}

H(flip)
S(flop)

1000 H(i) ^ S(o)

produces 
H(A) 0.99995
S(C) 0.99995
in Alchemy 2, which is what I expected, but however, very different from the previous result, where H(i) ^ S(o)
was set as a hard constraint.

In LoMRF, the corresponding result is 
H(A) 0.7103
S(C) 0.71625,

which I don't understand at all. It is different from the result produced by the previous .mln, where H(i) ^ S(o)
was set as a hard constraint, and different from the corresponding result of Alchemy 2.

Can someone please explain these results and/or correct my understanding of how LoMRF and Alchemy 2 work? 

First, a hard constraint should be roughly the same as a similar heavy weighted formula. This seems to hold in experiments (1) and (2) but does not seem to hold in experiment (3) and the formula H(i) ^ S(o), in both LoMRF and Alchemy 2.
Second, in the case of the heavy weighted formula 1000 H(i) ^ S(o), Alchemy 2 and LoMRF produce quite different results.

thanks in advance,
markos

**Comment by anskarl** [comment]
Hi @markos523

In MLNs inference is performed over the possible Herbrand interpretations and each state is has a probability that depends on the number of CNF clauses that satisfies. In all of the aforementioned examples there are four possible states {H(A), S(C)}, {H(A), !S(C)}, {!H(A), S(C)} and {!H(A), !S(C)}.

Please note that inference is performed in CNF form, therefore:

* formula: `H(i) v S(o)` remains the same in CNF
* formula: `H(i) => S(o)` is `!H(i) v S(o)`
* and formula `H(i) ^ S(o)`  is `!H(i) v !S(o)`

For the last one `H(i) ^ S(o)`, there are two different approaches that can be demonstrated using the `lomrf export` command. Similar to `lomrf infer`, in `lomrf export` there is a flag parameter `-noNegWeights`. To see what happens with that parameter, consider the last example (theory.mln) that you have provided:

```
flip = {A}
flop = {C}

H(flip)
S(flop)

1000 H(i) ^ S(o)
```

Using the defaults in LoMRF (i.e., noNegWeights is false), the export command below:

```
lomrf export -e empty.db -i theory.mln -q H/1,S/1 -f GROUND_CNF -o result.txt
```

produces the following output (result.txt):

```
// weighted ground clauses

-1000 !S(C) v !H(A)
```

However, by enabling the parameter `-noNegWeights`:

```
lomrf export -e empty.db -i theory.mln -q H/1,S/1 -f GROUND_CNF -o result.txt -noNegWeights
```

```
// weighted ground clauses

500 H(A)
500 S(C)
```

As a result, by setting `noNegWeights` flag in your last two examples will give the different results.

Hard-constrained formula `H(i) ^ S(o).` gives:

```
S(C) 1.0
H(A) 1.0
```
Similarly, the heavy weighted formula `1000 H(i) ^ S(o)` gives:

```
S(C) 0.999
H(A) 0.999
```

Perhaps Alchemy-2 uses the second approach only for soft-constrained formulas (i.e., noNegWeights enabled), that's why the output of LoMRF differs in the last example.

**Comment by markos523** [comment]
Hi @anskarl ,
many thanks for your answer, this cleared things a lot.
Sorry for the late reply...
