### ISSUE TITLE
Questions: Ojalgo, Inference with comments & option "-mapOutput"

### ISSUE THREAD

**Issue by rbrtjr** [anskarl/LoMRF#8]
Hello!

**1- Observation: When running "lomrf wlearn ...", the generated output includes comment like "//", however, when running the inference "lomrf infer ..."
I get this error:**

> ----------

[ERROR] Can't parse the following expression: '[2.1] failure: `#include' expected but `/' found

// Clauses

^' in file: 'dengue-learned.mln'

> ----------

**However, When I replace the original comments ("//") with "/ *...* /", it works**

> ----------

/* Clauses */
...

> ----------

**2-Question: When running the inference with the option "-mapOutput positive", the result is an empty file;
Am I using it wrong?**

> ----------

lomrf infer -inferType map -i dengue-learned.mln -e dengue-evidence.db -q Dengue/1,Zika/1,Chikungunya/1 -mapOutput positive -r out-map.txt 

> ----------

**3-When running inference whit option "-ilpSolver ojalgo", the app keeps lp_solver:**

> ----------

[INFO]
...
(ilpSolver) Solver used by ILP map inference: LPSolve
...

> ----------

**Thanks!**

**Comment by anskarl** [comment]
1. Can you provide an example file, in order to reproduce the error?

2. Positive only output gives the resulting ground predicates with True assigned values. In situations where all resulting ground predicates are False, then the resulting output file will be empty.

3. The info reporting message is wrong. LoMRF will eventually use ojalgo. 

Thanks for reporting the bug(s).

**Comment by rbrtjr** [comment]
**Hello!**
**Sure!**

**About the "comment" question:**

**With the example provided "\Examples\Weight_Learning\Friends_Smokers", I run**

> -----

lomrf wlearn -alg CDA -i smoking.mln -t smoking-train.db -o smoking-learned-CDA.mln -ne Smokes/1,Cancer/1 -lossAugmented -ilpSolver lpsolve

> -----

**The output file "smoking-learned-CDA.mln" has:**

> -----

// Predicate definitions
Friends(person,person)
Smokes(person)
Cancer(person)

// Clauses
-2 !Smokes(x) v Cancer(x)

0 !Friends(x,y) v !Smokes(x) v Smokes(y)

0 !Friends(x,y) v Smokes(x) v !Smokes(y)

> -----

**Then, I run**

> -----

lomrf infer -inferType map -mapType ilp -i smoking-learned-CDA.mln -r map.result -e smoking-test.db -q Smokes/1,Cancer/1

> -----

**and get the error:**

> -----

[ERROR] Can't parse the following expression: '[2.1] failure: `#include' expected but `/' found

// Clauses

^' in file: 'smoking-learned-CDA.mln'

> -----

**Replacing the comments (//) with `(/*...*/),` works fine>**

> -----

/* Predicate definitions */
Friends(person,person)
Smokes(person)
Cancer(person)

/* Clauses */
-2 !Smokes(x) v Cancer(x)

0 !Friends(x,y) v !Smokes(x) v Smokes(y)

0 !Friends(x,y) v Smokes(x) v !Smokes(y)

> -----

**About the "mapOutput", I think I didn´t undestand very well. A True assignment doestn mean "1" in the output file?**

**Thanks!**

**Comment by anskarl** [comment]
- I've run your example and I haven't noticed any issues with the parsing. Since the LoMRF is running on JVM it should have the same behaviour on Windows.

- When 'mapOutput' is 'all' (i.e., the default one), then the resulting file will contain all resulting ground atoms and each one will be associated with an integer number, where 0 is for False and 1 is for True. When  'mapOutput' is 'positive', then the resulting file will contain all resulting ground atoms that are True. I think that you only have False resulting ground atoms and therefore the resulting file is empty. What is the output when you set the 'mapOutput' as 'all'? If all the resulting output predicates are associated with 0 value (i.e., False) then it is correct to get an empty file when 'mapOutput' is set to 'positive', otherwise it is a bug.

**Comment by rbrtjr** [comment]
**Hello.**

**About the comments, it´s really weird... I run java 8 (B121)**

**About the mapOutput, using all/map:**

Excerpts: 

> ---

Chikungunya(R995) 1
Chikungunya(R994) 0
Chikungunya(R993) 1
Chikungunya(R992) 1
...
Dengue(R833) 0
Dengue(R832) 0
Dengue(R831) 1
Dengue(R830) 0
...
Zika(R7) 1
Zika(R6) 0
Zika(R5) 0
Zika(R4) 0
Zika(R3) 1
Zika(R2) 1

> ----

**About the mapOutput, using all/marginal:**
Excerpts: 

> ---

Chikungunya(R995) 0.999
Chikungunya(R994) 0.528
Chikungunya(R993) 0.443
Chikungunya(R992) 0.611
...
Dengue(R833) 0.134
Dengue(R832) 0.207
Dengue(R831) 0.0
Dengue(R830) 0.48
...
Zika(R7) 1.0
Zika(R6) 0.0
Zika(R5) 0.0
Zika(R4) 0.001
Zika(R3) 1.0
Zika(R2) 1.0

> ---

**Thanks!**
